apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-fleet-tester
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend-fleet-tester
  replicas: 3
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend-fleet-tester
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google-samples/gb-frontend:v5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
